Feature/cfos 102
MetaCell/cfos-visualizer pull request #39
Opened 2024-04-05 13:10 UTC by afonsobspinto

closes https://metacell.atlassian.net/browse/CFOS-102
closes https://metacell.atlassian.net/browse/CFOS-92

https://github.com/MetaCell/cfos-visualizer/assets/19196034/1ae6354a-9333-480c-b2c0-f2995a333073

To do:

- [ ] Update processor to include nifiti datatypeCode
- [ ] Address atlas wireframe
- [ ] Position tooltip at the mouse location (do we still want to do this @ddelpiano ?)
- [ ] Some UI look and feel touches (like not showing undefined f.e., show only visible activity maps)

2024-04-05 14:35 UTC, afonsobspinto commented
Given the map details introduction I don't see much value in the tooltip anymore. I find it a bit distracting and I don't like that it  overlaps with the viewer

2024-04-11 17:04 UTC, aranega requested changes
All looks good :) there is perhaps just a question I have about one line and a syntax I'm not aware of, beside that all nice! :+1:

2024-04-11 17:15 UTC, afonsobspinto commented on client/src/components/Viewer.js
> +        if (currentAtlas, sliceIndex && sliceIndex < currentAtlas.orientationMaxIndex - 1) {
It's a typo. Thanks. Great eye 🦅

2024-04-11 18:27 UTC, aranega approved these changes
Thanks! I really wasn't sure it was a hidden js syntax feature I didn't know :sweat_smile:

2024-04-11 18:29 UTC, aranega commented
I'll use your branch as base for CFOS-71

2024-04-11 21:09 UTC, ddelpiano commented
@afonsobspinto could you please solve the conflicts here? Thanks!

2024-04-11 21:40 UTC, afonsobspinto commented
> @afonsobspinto could you please solve the conflicts here? Thanks!

done ✅

2024-04-11 23:50 UTC, aranega approved these changes

2024-04-12 08:43 UTC, merged